version: "2"
run:
  relative-path-mode: gomod

linters:
  default: all
  disable:
    - wsl # deprecated # using wsl_v5 instead
    - gomodguard # deprecated # using gomodguard_v2 instead
  settings:
    interfacebloat:
      max: 15
    funlen:
      lines: 90
      statements: 60
      ignore-comments: true
    exhaustruct:
      include:
        - 'github.com/efeligne/screen-arch\..+'
      exclude: []
      allow-empty: true
      allow-empty-returns: true
      allow-empty-declarations: true
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - "2"
        - "-1"
      ignored-files:
        - '_test\.go$'
        - '_generated\.go$'
        - "vendor/"
      ignored-functions:
        - '^math\.'
        - '^http\.StatusText$'
        - '^time\.(Date|Parse|Unix|Duration)$'
        - '^strconv\.'
        - '^strings\.'
        - '^bytes\.'
        - '^os\.(OpenFile|Chmod|Mkdir|MkdirAll)$'
        - '^syscall\.Chmod$'
        - "^make$"
        - "^append$"
        - "^copy$"
        - "^len$"
        - "^cap$"
    gocognit:
      min-complexity: 40
    gocyclo:
      min-complexity: 30
    spancheck:
      checks:
        - end
        - record-error
        - set-status
    revive:
      enable-all-rules: true
      rules:
        - name: var-naming
          severity: error
          disabled: false
          exclude: []
          arguments:
            - [] # AllowList
            - [] # DenyList
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          arguments: [7]
        - name: unhandled-error
          severity: error
          disabled: false
          exclude: []
          arguments:
            - '^strings\.Builder\.(Write|WriteByte|WriteRune|WriteString)$'
            - '^fmt\.(Print|Printf|Println|Sprintf|Fprint|Fprintf|Fprintln|Scanf)$'
            - '^io\.PipeWriter\.CloseWithError$'
        - name: add-constant
          disabled: true # use mnd instead
        - name: function-length
          disabled: true # use funlen instead
        - name: cyclomatic
          disabled: true # use gocyclo instead
        - name: cognitive-complexity
          disabled: true #use gocognit instead
    nlreturn:
      block-size: 2
    varnamelen:
      max-distance: 0
      min-name-length: 3
      check-receiver: false
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names:
        - in # useful word
        - to # useful word
        - tt # test cases
        - db # database
        - id # identifier
      ignore-decls:
        - t testing.T
        - i int
        - j int
        - ok bool
        - q string # query
        - T any
        - wg sync.WaitGroup
        - re *regexp.Regexp
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd # стандартная библиотека Go
            - github.com/efeligne/screen-arch
            - github.com/efeligne/screen-arch/
            - github.com/gin-gonic/gin
            - github.com/stretchr/testify
          deny: []
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor/.*
      - .*_generated.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - gofmt
    - gci
    - golines
  settings:
    gofumpt:
      extra-rules: true
      module-path: github.com/efeligne/screen-arch
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
        - pattern: "make([]byte, 0)"
          replacement: "[]byte{}"
        - pattern: "make([]byte, 0, 0)"
          replacement: "[]byte{}"
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/efeligne/screen-arch)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - vendor/.*
      - .*_generated.go
      - third_party$
      - builtin$
      - examples$
