[tools]
go = "1.24.2"
golangci-lint = "2.12.2"

[vars]
app_name = 'screen-arch'
build = 'go build'
run = 'go run'
golangci = 'golangci-lint'
linter = '{{vars.golangci}} run --config=.golangci.yml'

[tasks]
dev = '{{vars.run}} main.go'
build = '{{vars.build}} -o ./{{vars.app_name}} .'
lint = ['{{vars.golangci}} cache clean', '{{vars.linter}} ./...']
format = [
  '{{vars.golangci}} cache clean',
  '{{vars.linter}} --fix --issues-exit-code=0 ./... >/dev/null && echo "Done!" ',
]
install = [
  'test ! -f /usr/local/bin/{{vars.app_name}} || (echo "error: /usr/local/bin/{{vars.app_name}} already exists, aborting" && exit 1)',
  '{{vars.build}} -o ./{{vars.app_name}} .',
  'sudo cp ./{{vars.app_name}} /usr/local/bin/{{vars.app_name}}',
]
launch_agent = [
  'cp com.efeligne.screen-arch.plist ~/Library/LaunchAgents',
  'launchctl load ~/Library/LaunchAgents/com.efeligne.screen-arch.plist',
]
